/**
 * Pokemon API Specification
 * API Specification that guide users/developers how the system is structured.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetPokemonByID200Response { 
    ability?: Array<object>;
    base_experience?: number;
    cries?: object;
    forms?: Array<object>;
    game_indices?: object;
    height?: number;
    held_items?: Array<object>;
    id?: number;
    is_default?: boolean;
    location_area_encounters?: string;
    moves?: Array<object>;
    name?: string;
    order?: number;
    past_abilities?: Array<object>;
    past_types?: Array<object>;
    species?: object;
    sprites?: object;
    stats?: Array<object>;
    types?: Array<object>;
    weight?: number;
}

